### PR TITLE
Add bower.json for package register, see https://github.com/bower/bower....

### PR DESCRIPTION
**Pull request by xhochn**
...json-spec

### CODE REVIEW

**Comment by martinandert** [comment]
It seems to be not as easy as having a bower.json and pushing to bower's registry. What about the pluralizers for locales other than "en"? Those are to be require'd on demand actually. 

Also, this library uses the CommonJS ecosystem provided by Node.js and thus cannot be used in a standalone fashion. Normally one would use tools like browserify or webpack to integrate the pluralizers module on the client-side.

**Comment by xhochn** [comment]
All files in your repro, will be included in the bower package.
You are right with the CommonJS dependencies, i will search a solution.

**Comment by xhochn** [comment]
It looks like, the CommonJS ecosystem, is no problem ;)

"A packaged component can be made up of any type of asset, and use any type of transport (e.g., AMD, CommonJS, etc.)."

**Comment by martinandert** [comment]
Closing this as bower is officially dead.

**Pull request closed without merging**
